config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  devise_for :users
  
  get '/seen', to: 'announcements#mark_as_seen'
  
  resources :users, only: [:show]
  resources :announcements, only: [:create, :destroy, :index, :edit, :update]
  
end

app/models/announcement.rb
class Announcement < ApplicationRecord
  validates :content, presence: true, length: { maximum: 140 }
  validates :expiration_date, presence: true
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  validates :name, presence: true, length: { maximum: 20 }
  validates :last_name, presence: true, length: { maximum: 20 }
  has_many :announcements
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy, :index, :edit, :update]
  
  def index
    @announcements = Announcement.where.not(id: cookies.signed[:seen_announcements])
                                 .where("expiration_date >= ?", Date.today)
  end
  
  def create
    @announcement = current_user.announcements.build(announcement_params)
    if @announcement.save
      flash[:notice] = "Announcement created!"
      redirect_to announcements_url
    else
      redirect_to announcements_url
      flash[:alert] = "Announcement couldn't be created."
    end
  end

  def destroy
  end
  
  def mark_as_seen
    seen_announcements = cookies.signed[:seen_announcements] || []
    seen_announcements = seen_announcements << params[:announcement]
    
    cookies.signed[:seen_announcements] = seen_announcements
    flash[:notice] = 'Marcado como visto'
    redirect_to announcements_url
  end

  private

    def announcement_params
      params.require(:announcement).permit(:content, :expiration_date)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :last_name])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @announcement = current_user.announcements.build if user_signed_in?
  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
  def full_name(id)
    user = User.find(id)
    return "#{user.name} #{user.last_name}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
 def devise_error_messages!
  return '' if resource.errors.empty?

   messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
   sentence = I18n.t('errors.messages.not_saved',
   count: resource.errors.count,
   resource: resource.class.model_name.human.downcase)

   html = <<-HTML
   <div class="callout alert">
    <h4>#{sentence}</h4>
    #{messages}
   </div>
   HTML

   html.html_safe
 end
end

app/helpers/seen_announcements_helper.rb
module SeenAnnouncementsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/announcements/index.html.erb
<% provide(:title, 'Announcements') %>
<h1>Announcements</h1>

<%= link_to "Create new announcement", current_user %></li>
<% @announcements.each do |a| %>
  <div class="callout">
    <p><%= "Made by: #{full_name(a.user_id)}" %></p>
    <h4><%= a.content %></h5>
    <p><%= "Valid until #{a.expiration_date}" %></p>
    <a href=<%= url_for :action => :mark_as_seen, :announcement => a %>> Mark as seen </a>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">Announcements App</li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li><%= link_to "Home", root_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to "Announcements", announcements_path %></li>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Log in", new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="row columns">
      <p></p>
    </div>
      <% if notice %>
        <div class="callout success"><%= notice %></div>
      <% end %>
      <% if alert %>
        <div class="callout alert"><%= alert %></div>
      <% end %>
      <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @announcement.errors.any? %>
  <div class="callout alert">
    The new announcement contains <%= pluralize(@announcement.errors.count, "error") %>.
    <ul>
      <% @announcement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<div class="card float-center" style="width: 80%;">
  <div class="card-section">
    <h2 class="text-center">Welcome to the Announcement App! </h2>
  </div>
  <% if user_signed_in? %>
    <div class="card-section">
      <p class="text-center">Create announcements to inform other users whatever you want.</p>
      <p class="text-center">Mark announcements as seen if they're no longer important to you!</p>
      <p class="text-center">Choose how long you want your announcements to remain valid.</p>
    </div>
  <% else %>
    <div class="card-section">
      <h3 class="text-center"><%= link_to "Log in", new_user_session_path %> to start creating announcements!</h3>
      <h5 class="text-center">Or <%= link_to "create an account", new_user_registration_path %></h5>
    </div>
  <% end %>
</div>

app/views/users/shared/_links.html.erb
<div class="grid-container">
  <div class="grid-x grid-padding-x">    
    <%- if controller_name != 'sessions' %>
      <%= link_to "Log in", new_session_path(resource_name) %><br />
    <% end -%>
    
    <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
      <%= link_to "Sign up", new_registration_path(resource_name) %><br />
    <% end -%>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "#{@user.name} #{@user.last_name}") %>
<div class="row columns">
  <h3><%= "Hello, #{@user.name} #{@user.last_name}!" %></h3>
</div>
   <%= form_for(@announcement) do |f| %>
    <div class="grid-container">
      <div class="grid-x grid-padding-x">
        <div class="medium-8 cell">
          <%= f.label :content, "Your announcement" %>
          <%= f.text_area :content, placeholder: "Create public announcement" %>
        </div>
        <div class="medium-4 cell">
          <%= f.label :expiration_date, "Expiration date" %>
          <%= f.date_field :expiration_date %>
        </div>
      </div>
      <%= f.submit "Post", class: "button float-right" %>
    </div>
  <% end %>
</div>